### ISSUE TITLE
unable to send to other user than pre-configured user/channel in rocket.chat integration

### ISSUE THREAD

**Issue by ttamirt** [Open-Future-Belgium/zabbix-Rocket.Chat#2]
Cannot send alert to another user or channel. In Slack version, it can send to other users. It uses to="$1" and sends to another user. Which helps me to send different alerts to different users, channels with just one webhook.

**Comment by Trikke76** [comment]
i know it's a limitation atm. I will try to fix this but for this i need some time to rewrite the code
feel free to send me a pr if you fix it as it will not be for anytime soon.
