### ISSUE TITLE
Can't get Zabbix to send the alert.

### ISSUE THREAD

**Issue by tiredofit** [Open-Future-Belgium/zabbix-Rocket.Chat#3]
Zabbix 3.4.5 - File sitting in /usr/lib/zabbix/alertscripts/rocketchat.sh 
Has appropriate permissions for executing. Can execute from bash, sends a semi colon to my Rocketchat Instance.

Have setup the Media Type and script `rocketchat.sh`
Have setup a user with notification set to use rocketchat.sh
Have created the Default Message as per shown example. Nothing. I get email notifications, but even looking at the Reports of Notifications shows that the Rocketchat script isn't fired. Log's aren't saying much. Any advice?

**Comment by Trikke76** [comment]
Hi,

i just upgraded my zabbix from 3.2 to 3.4 and the script still works
try to send something from command line with the script if this works it is maybe due to a formatting error in your action / conditions

i noticed that someone made a PR for an issue with the log thats why you see nothing in it
you can remove the 1 in front and just keep

 >>${LOGFILE} 2>&1

then you will get a log of all messages and errors in the log file

**Comment by hubars** [comment]
Hi,
this configuration works fine for me:

1. Script path
/usr/lib/zabbix/alertscripts/rocket-chat/rocket.sh/rocket.sh

2. Make a file executable
chmod +x rocket.sh && chown zabbix.zabbix rocket.sh

3. Add new Media Type
![rocket_zabbix_01](https://user-images.githubusercontent.com/36196579/51390157-c93a5680-1b2e-11e9-9bb9-016d3b8e2c3a.png)

4. Add Action
![rocket_zabbix_02](https://user-images.githubusercontent.com/36196579/51390219-f7b83180-1b2e-11e9-9bfd-070720e9a213.png)
![rocket_zabbix_03](https://user-images.githubusercontent.com/36196579/51390223-fdae1280-1b2e-11e9-88e5-f630bae318b0.png)
 
5. Add new Medua Type in setting User (sebbix)
![rocket_zabbix_04](https://user-images.githubusercontent.com/36196579/51391409-47e4c300-1b32-11e9-9c6b-7b131dec124d.png)

6. Add new incoming WebHook in Rocket.Chat and copy Webhook URL to script rocket.sh
7. Add new user in Rocket.Chat (sebbix) and add the same username in script rocket.sh

**Comment by wit12345** [comment]
Hi, 

I have to create an user on zabbix server? In your case the sebbix?

Thank you

**Comment by hubars** [comment]
Hi,
yes - in my case i have the same name of user in zabbix and rocket.chat.

**Comment by wit12345** [comment]
Hi,

When I execute from bash, sends a notification to my Rocketchat Instance with success but with the Web configuration I can't get my notifications on Rocket Chat. 

I've looked in my Reports of Notifications and shows that the Rocketchat script is fired with success but I can't understand what I've missed.

Can you help me ?

**Comment by Trikke76** [comment]
probably the information that you send has an issue
try to send a simple short text string
probably it will work

**Comment by wit12345** [comment]
Hi, 
Yes , with simple text works fine for the Problem but for OK or ACK I didin't get any notifications

**Comment by Trikke76** [comment]
maybe check the header 
can be an issue in the header name as it should work the same way for all notifications

**Comment by wit12345** [comment]
It's working now. It's seems the messages have to be simple, for example in OK to work I have changed the default message to: 

`Default subject OK: {HOST.HOST}

Default message {TRIGGER.NAME}
` 
and now it's working fine.

Thank you all

**Comment by Trikke76** [comment]
ok gr8

feel free to improve the script if you want
i will close this for now 
and try to improve it when i have some free time
